c4:
    dataset_name: c4
    num_samples: 100
    data_files:
        validation: "en/c4-validation.00000-of-00008.json.gz"
    remove_columns: ["url", "timestamp"]
    split: validation
    use_label: True
    max_length: 256

wikitext:
    dataset_name: wikitext
    num_samples: 100
    data_files:
        validation: "wikitext-2-raw-v1/train-00000-of-00001.parquet"
    split: validation
    use_label: True
    max_length: 256

mixed:
    dataset_name: mixed
    base_datasets:
        - dataset_name: wikitext
          data_files:
              validation: "wikitext-2-raw-v1/train-00000-of-00001.parquet"
        - dataset_name: mmlu
          data_files:
              validation: "all/validation-00000-of-00001.parquet"
    split: validation
    use_label: True
    max_length: 256
    # Here, num_samples means the number of samples per dataset
    num_samples: 5

data_loader:
    batch_size: 1
    shuffle: False
