dataset:
    dataset_name: wikitext
    num_samples: 100
    data_files:
        validation: "wikitext-2-raw-v1/train-00000-of-00001.parquet"
    split: validation
    use_label: True
    max_length: 256

data_loader:
    batch_size: 1
    shuffle: False
