_base_: ['./llama2_7b_per_attn.yaml']

model:
    model_name: "meta-llama/Llama-2-70b-hf"
    tokenizer_name: "meta-llama/Llama-2-70b-hf"
    manual_dispatch: True
    dispatch_cfg:
        checkpoint: "{{$HF_HOME:~/.cache/huggingface}}/hub/models--meta-llama--Llama-2-70b-hf/snapshots/3aba440b59558f995867ba6e1f58f21d0336b5bb"
        offload_folder: offload
        offload_state_dict: True
        no_split_module_classes:
            - "LlamaDecoderLayer"
    model_args:
        torch_dtype: bfloat16
