data_loader:
    batch_size: 16
    shuffle: False

ckpt_path: "./workdirs/bert-imdb-finetuned/checkpoint-188"

pruner:
    type: ForwardPruner
    dual_insert_layer: bert.embeddings
    criterion:
        scope: "global_thres"
        strategy: "forward_grads"
    sparsities: [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]

test_cfg:
    # testing time sparsity can be a subset of pruning time sparsity
    sparsities: [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
    exclude_layers: ["embeddings", "LayerNorm", "classifier"]
    use_prior: False
