dataset:
    num_samples: 3000
    use_label: False

data_loader:
    batch_size: 1
    shuffle: False

pruning_dir: "./workdirs/prune_bert/"
ckpt_path: "./workdirs/bert-imdb-finetuned/checkpoint-188"

pruner:
    type: ForwardPruner
    dual_insert_layer: model.embed_tokens
    criterion:
        scope: "global"
        strategy: "forward_grads"
        exclude_layers: ["embed_tokens", "norm", "lm_head", "self_attn"]
    sparsities: [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4]

test_cfg:
    # testing time sparsity can be a subset of pruning time sparsity
    sparsities: [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4]
    use_prior: False
    testing_manager:
        type: ForwardPrunerTestingManager
